import TanStackProviders from '@/lib/react-query/QueryProvider';
import './globals.css';
import StyledComponentsRegistry from '@/lib/styled-components/registry';
import { ReduxProviders } from '@/lib/redux/ReduxProvider';
import Link from 'next/link';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko-kr">
            <body>
                <ReduxProviders>
                    <TanStackProviders>
                        <StyledComponentsRegistry>
                            <h3>
                                <Link href="/">Home</Link>
                            </h3>
                            <h3>
                                <Link href="/initial-data">Prefetching Using initial data</Link>
                            </h3>
                            <h3>
                                <Link href="/hydration">Prefetching Using Hydration</Link>
                            </h3>
                            {children}
                        </StyledComponentsRegistry>
                    </TanStackProviders>
                </ReduxProviders>
            </body>
        </html>
    );
}
