import TanStackProviders from '@/lib/react-query/QueryProvider';
import './globals.css';
import StyledComponentsRegistry from '@/lib/styled-components/registry';
import { ReduxProviders } from '@/lib/redux/ReduxProvider';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko-kr">
            <body>
                <ReduxProviders>
                    <TanStackProviders>
                        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
                    </TanStackProviders>
                </ReduxProviders>
            </body>
        </html>
    );
}
